COLUMNS:
  LIMIT_BAL: int
  SEX: int
  EDUCATION: int
  MARRIAGE: int
  AGE: int
  PAY_0: int
  PAY_2: int
  PAY_3: int
  PAY_4: int
  PAY_5: int 
  PAY_6: int 
  BILL_AMT1: int  
  BILL_AMT2: int  
  BILL_AMT3: int  
  BILL_AMT4: int  
  BILL_AMT5: int  
  BILL_AMT6: int  
  PAY_AMT1: int  
  PAY_AMT2 : int  
  PAY_AMT3 : int   
  PAY_AMT4 : int  
  PAY_AMT5: int  
  PAY_AMT6: int   
  default payment next month: int


TARGET_COLUMN:
  name:  default payment next month
