artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/saikiran7288/Data-Store/raw/main/default_credit.zip
  local_data_file: artifacts/data_ingestion/default_credit.zip
  unzip_dir: artifacts/data_ingestion

  